### ISSUE TITLE
Too much data

### ISSUE THREAD

**Issue by rpaterson** [singer-io/tap-marketo#11]
A good 50% of the output  that `tap-marketo` produces are Activities of `type=13`, "Change Data Value".  These are not really useful to us - they're just a cue to reload the associated Lead which `tap-marketo` is already doing, there's no need to emit the activity as well.  Could you change `tap-marketo` to not emit Activities with `type=13` (but still load them from Marketo and update the Lead)?

**Comment by iterati** [comment]
What about type=12 which indicates a new lead was created? That info is mirrored in the "createdAt" timestamp, more or less. I think the suggestion is a good one, but it does in some ways require the tap to have an opinion on what data is useful and what is not. That's something we're trying to avoid. Blacklisting activity types seems like the way to go in that case.

**Comment by rpaterson** [comment]
Sure type=12 is even less useful to emit.  A blacklist of activity types sounds good to me.  I can probably contribute a patch for this if you could describe what form that blacklist would take?

**Comment by iterati** [comment]
@rpaterson I've merged the latest version of our bulk api branch into the master earlier. The way blacklisting would work is that each activity type will have it's own table with all of the attributes flattened to columns. If you find that you don't want a particular activity type, you can just not select that activity type to be synced.

**Comment by rpaterson** [comment]
That sounds great - thank you!
