### ISSUE TITLE
Add ability to white-list or black-list Lead custom fields

### ISSUE THREAD

**Issue by rpaterson** [singer-io/tap-marketo#13]
I sync Marketo -> Redshift using this tap and Salesforce -> Redshift using StitchData.  I also sync Salesforce -> Marketo (I think that's built-in to Marketo?).  Most of the fields in Marketo Leads actually originate from Salesforce, and with this system I'm syncing them in to Redshift twice!  It would be really nice if this tap supported whitelisting or blacklisting the Lead custom fields.  I would use that to exclude fields which actually originate in Salesforce.

**Comment by rpaterson** [comment]
In my perfect world this tap would automatically figure out which custom fields originally come from Salesforce and blacklist those, but that's probably too much to hope for :-)

**Comment by iterati** [comment]
Table and field selection is enabled in the current master branch. Automatic detection of fields is out of scope for the tap, but you can now ensure that you only get useful rows.
