### ISSUE TITLE
Leads and Activities too slow - have to use Bulk API

### ISSUE THREAD

**Issue by rpaterson** [singer-io/tap-marketo#9]
The current implementation of downloading Leads and Activities is too slow for our Marketo volume.  We have ~2M Leads and produce ~1M Activities per day, most of them Lead modifications.  Even with the recent bump to 8000 requests per day `tap-marketo` can't even keep up with our daily steady-state Marketo volume, much less do the initial sync (which requires loading _all_ of our historical Activities going back several years to pick up all the Leads we have today).  I've done some prototyping with the new Marketo Bulk API and I think that is the only way that can support our Marketo volume.

I had some initial concerns about Marketo's Bulk API daily download quota, but I recently made a discovery about that which will make using the Bulk API workable.  The [Marketo Bulk API limit doc](http://developers.marketo.com/rest-api/bulk-extract/#file_size) says `The daily quota is a maximum of 500MB per day`.  However if you read the fine print what it actually says is that after you _exceed_ 500MB per day you can not enqueue another Bulk API job.  That means that the last job which you enqueue in a day before you exceed your quota can be _more_ than 500MB.  Note there is still the additional limitation of downloading at most 30 days of data at once.  I've tried this and was able to download a full month's worth of our Activities at over 5GB with a single Bulk API request!  I know that Singer Taps are generally not supposed to use up the entire API quota, but in this case there is a major benefit in doing so.  Below I'm going to refer to this as "overflowing" the quota.

Here's how the Lead and Activities steady-state sync algorithm would work using the Bulk API:
1) Bulk download Activities created since last run (205bytes/activity * estimated 1M activities/day = 205Mb per day)
2) Bulk download Leads created since last run (410 bytes/lead = 1.2M Leads per day at quota, virtually unlimited if willing to overflow quota as described above)
3) Use REST API to download updated Leads mentioned in Activities above, 300 at a time (same as existing implementation, estimated 400k Leads/day = 1400 API calls/day, easily within quota)

For the initial sync we would first need to get all the current Leads.  We bulk download them by creation date, working forwards from the first Activity in Marketo (410 bytes/Lead => 1.2M Leads per day at quota, so a couple days to complete).  Note can't take advantage of overflowing the quota here because of the 30 day limitation.

Finally once we've got the steady-state sync going, we can use the last request of the day to download historical Activities (30 days of historical Activities per day of real time, overflowing the quota).  My Marketo database is a couple of years old, so it would take a bit more than a month to fully download all the historical Activities.

**Comment by rpaterson** [comment]
Does this sound viable?  Would you be willing to change `tap-marketo` to support our Marketo volume or will we need to fork it?

**Comment by rpaterson** [comment]
@awm33 @karstendick @mdelaurentis @briansloane

**Comment by briansloane** [comment]
@rpaterson I discussed the bulk API with Marketo via their developer office hours to determine if this approach is viable. They stated that it is acceptable to make a request to the Bulk API that will return more than 500MB and then any follow-up requests will have to wait until the following day. Based on that feedback, your suggested approach of "overflowing" sounds like it will work and would be a great solution to see implemented into the Tap. 

While we don't have a specific timeline for making these changes at Stitch, we would be comfortable with this approach being implemented in the future.

**Comment by rpaterson** [comment]
Great!  We may try to do this ourselves, but I'm not sure when.  I'll post
here if we start work on it.

**Comment by iterati** [comment]
@rpaterson Thank you for the research. I'll be updating the tap to support the bulk API. If you have any questions I'm on the singer slack as `iterati`.

**Comment by rpaterson** [comment]
Cool!  It turns out that I had overestimated our Marketo volume (I probably sampled a few unusually busy days) and the existing implementation is able to keep up with us.  However the initial sync took several weeks.

**Comment by iterati** [comment]
The tap uses too many requests in general. The leads endpoint has to chunk fields because every field needs to be in the query string and some clients have more than 600 fields on their leads. That's 7 requests per 100 leads! And you have 2M!

**Comment by rpaterson** [comment]
Why was PR #12 closed?  Is this work not going forward?

**Comment by iterati** [comment]
@rpaterson No, my teammate and I are taking some of those changes into a new branch. We are starting testing today. We've got bulk working for leads with and without Corona support and for activities.

**Comment by iterati** [comment]
Bulk api support was the main focus of the new version of the tap that's currently in the master branch. Closing this issue. Thank you again for the research @rpaterson .
